
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LT = 13;
  public static final int identifier = 22;
  public static final int RPAREN = 10;
  public static final int IDENTIFIER = 21;
  public static final int OTHERWISE = 12;
  public static final int IF = 11;
  public static final int LPAREN = 9;
  public static final int GT = 14;
  public static final int ASSIGN_BODY_METHOD = 18;
  public static final int FLOAT_KEYWORD = 7;
  public static final int NAT = 2;
  public static final int STRING = 3;
  public static final int COMMA = 8;
  public static final int FLOAT = 4;
  public static final int LTEQ = 15;
  public static final int EOF = 0;
  public static final int STRING_KEYWORD = 6;
  public static final int ARROWS = 19;
  public static final int NAT_KEYWORD = 5;
  public static final int MINUS = 20;
  public static final int error = 1;
  public static final int EQ = 17;
  public static final int GTEQ = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NAT",
  "STRING",
  "FLOAT",
  "NAT_KEYWORD",
  "STRING_KEYWORD",
  "FLOAT_KEYWORD",
  "COMMA",
  "LPAREN",
  "RPAREN",
  "IF",
  "OTHERWISE",
  "LT",
  "GT",
  "LTEQ",
  "GTEQ",
  "EQ",
  "ASSIGN_BODY_METHOD",
  "ARROWS",
  "MINUS",
  "IDENTIFIER",
  "identifier"
  };
}

